version: "3.8"


services:
  gateway-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - microservices-network
    depends_on:
      - patient-service
      - note-service
      - diabetes-risk-service

  patient-service:
    build:
      context: ../patient-management-microservice  # Le chemin relatif vers le répertoire patient-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - microservices-network

  note-service:
    build:
      context: ../note-service  # Le chemin relatif vers le répertoire note-service
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    networks:
      - microservices-network

  diabetes-risk-service:
    build:
      context: ../diabetes-risk-microservice  # Le chemin relatif vers le répertoire diabetes-risk-service
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    networks:
      - microservices-network

  frontend-service:
    build:
      context: ../frontend-service  # Le chemin relatif vers le répertoire frontend-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge